### PR TITLE
Feature fix docker compose.yml

### PR DESCRIPTION
**Pull request by aiirononeko**
# やったこと
- コンテナ起動時にDBの作成とマイグレーションをするようにdocker-compose.ymlを修正
- ルートディレクトリにあった不要なpackage.jsonを削除

## 補足
- DBのコンテナが起動していない状態でapiコンテナを立ち上げると、コネクションエラーが発生してコンテナが立ち上がらない。
  →　解決策として、下記の順にコマンドを実行する（DBコンテナを起動した状態でAPIコンテナを起動する）
```shell
docker-compose up
```
```shell
docker-compose up -d
```

### CODE REVIEW

**Comment by show-coco** [comment]
補足の部分に関してですが、`depends_on`で起動順が制御されるはずじゃないですか？

[Docker: depends_on](http://docs.docker.jp/compose/compose-file.html#depends-on)

**Comment by aiirononeko** [comment]
言われてみれば確かに。。
調査して、プルリク更新させていただきます！

**Comment by aiirononeko** [comment]
エラーログ↓

`api_1              | Can't connect to MySQL server on 'db' (111 "Connection refused")
api_1              | Couldn't create 'languageMemoApp_development' database. Please check your configuration.
api_1              | rails aborted!
api_1              | Mysql2::Error::ConnectionError: Can't connect to MySQL server on 'db' (111 "Connection refused")
api_1              | /usr/local/bundle/gems/mysql2-0.5.3/lib/mysql2/client.rb:90:in `connect'
api_1              | /usr/local/bundle/gems/mysql2-0.5.3/lib/mysql2/client.rb:90:in `initialize'
api_1              | /usr/local/bundle/gems/activerecord-5.2.4.1/lib/active_record/connection_adapters/mysql2_adapter.rb:22:in `new'
api_1              | /usr/local/bundle/gems/activerecord-5.2.4.1/lib/active_record/connection_adapters/mysql2_adapter.rb:22:in `mysql2_connection'
api_1              | /usr/local/bundle/gems/activerecord-5.2.4.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:830:in `new_connection'
api_1              | /usr/local/bundle/gems/activerecord-5.2.4.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:874:in `checkout_new_connection'
api_1              | /usr/local/bundle/gems/activerecord-5.2.4.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:853:in `try_to_checkout_new_connection'
api_1              | /usr/local/bundle/gems/activerecord-5.2.4.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:814:in `acquire_connection'
api_1              | /usr/local/bundle/gems/activerecord-5.2.4.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:538:in `checkout'
api_1              | /usr/local/bundle/gems/activerecord-5.2.4.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:382:in `connection'
api_1              | /usr/local/bundle/gems/activerecord-5.2.4.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:1033:in `retrieve_connection'
api_1              | /usr/local/bundle/gems/activerecord-5.2.4.1/lib/active_record/connection_handling.rb:118:in `retrieve_connection'
api_1              | /usr/local/bundle/gems/activerecord-5.2.4.1/lib/active_record/connection_handling.rb:90:in `connection'
api_1              | /usr/local/bundle/gems/activerecord-5.2.4.1/lib/active_record/tasks/mysql_database_tasks.rb:6:in `connection'
api_1              | /usr/local/bundle/gems/activerecord-5.2.4.1/lib/active_record/tasks/mysql_database_tasks.rb:14:in `create'
api_1              | /usr/local/bundle/gems/activerecord-5.2.4.1/lib/active_record/tasks/database_tasks.rb:119:in `create'
api_1              | /usr/local/bundle/gems/activerecord-5.2.4.1/lib/active_record/tasks/database_tasks.rb:139:in `block in create_current'
api_1              | /usr/local/bundle/gems/activerecord-5.2.4.1/lib/active_record/tasks/database_tasks.rb:316:in `block in each_current_configuration'
api_1              | /usr/local/bundle/gems/activerecord-5.2.4.1/lib/active_record/tasks/database_tasks.rb:313:in `each'
api_1              | /usr/local/bundle/gems/activerecord-5.2.4.1/lib/active_record/tasks/database_tasks.rb:313:in `each_current_configuration'
api_1              | /usr/local/bundle/gems/activerecord-5.2.4.1/lib/active_record/tasks/database_tasks.rb:138:in `create_current'
api_1              | /usr/local/bundle/gems/activerecord-5.2.4.1/lib/active_record/railties/databases.rake:29:in `block (2 levels) in <top (required)>'
api_1              | /usr/local/bundle/gems/railties-5.2.4.1/lib/rails/commands/rake/rake_command.rb:23:in `block in perform'
api_1              | /usr/local/bundle/gems/railties-5.2.4.1/lib/rails/commands/rake/rake_command.rb:20:in `perform'
api_1              | /usr/local/bundle/gems/railties-5.2.4.1/lib/rails/command.rb:48:in `invoke'
api_1              | /usr/local/bundle/gems/railties-5.2.4.1/lib/rails/commands.rb:18:in `<top (required)>'
api_1              | /usr/local/bundle/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require'
api_1              | /usr/local/bundle/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `block in require_with_bootsnap_lfi'
api_1              | /usr/local/bundle/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
api_1              | /usr/local/bundle/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `require_with_bootsnap_lfi'
api_1              | /usr/local/bundle/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
api_1              | /usr/local/bundle/gems/activesupport-5.2.4.1/lib/active_support/dependencies.rb:291:in `block in require'
api_1              | /usr/local/bundle/gems/activesupport-5.2.4.1/lib/active_support/dependencies.rb:257:in `load_dependency'
api_1              | /usr/local/bundle/gems/activesupport-5.2.4.1/lib/active_support/dependencies.rb:291:in `require'
api_1              | bin/rails:4:in `<main>'
api_1              | Tasks: TOP => db:create
api_1              | (See full trace by running task with --trace)`

- コンテナの起動順序はdepends_onで設定しているから今回のエラーとは関係ないかも

**Comment by aiirononeko** [comment]
# 試したこと
- DBコンテナの外部ポート確認

**Comment by show-coco** [comment]
多分ここら辺が関係してくるかと...?

- [Dockerの環境構築で`could not connect to server: Connection refused`のエラーが出た時の対処法](https://qiita.com/yuki_0920/items/84e2ca260bfe13cf3072)
- [MySQLに外部接続できない時のチェックポイント](https://miningoo.com/81/)

**Comment by aiirononeko** [comment]
>結論としてはこのエラーは、config/database.ymlのhostをデーターベースのコンテナ名に指定することで解決しました。
→　hostは元々dbで指定している　→　二回目以降はdb:createできるので原因としては別にある気がする
エビデンス↓
`default: &default
  adapter: mysql2
  encoding: utf8
  host: db
  username: root
  password: password
  socket: /tmp/mysql.sock`

>MySQLはデフォルトでは外部ホストからの接続を許可しない設定になっています。
→　現在、3306ポートを開けて外部からの接続を許可している　→　これも二回目のdocker-compose up では正常にdbがcreateされるので原因は別にある気がする...

エビデンス↓
`  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: root
    ports:
      - "3306:3306"`

**Comment by aiirononeko** [comment]
wait-for-it.shを使用する事で初回起動時にDBコンテナとコネクションエラーででる事象を解決。

**Comment by show-coco** [comment]
このブランチを通して作成した記事(By Ryota)↓
https://qiita.com/aiiro_engineer/items/5c6158748353d4c66095

**Pull request merged**
